AWSTemplateFormatVersion: '2010-09-09'
Description: sam template for cf deployment lambda
Parameters:
  AutomationRole:
    Default: arn:aws:iam::892774835300:role/ThousandServersBootstrap-AutomationRole-1HQFBRP4LDTPX
    Description: ARN of the role to be used by the CodePipeline service - Get the
      ARN from the bootstrap stack outputs
    Type: String
Resources:
  LambdaFunction:
    Properties:
      CodeUri: s3://sam-us-east-1-892774835300/fec2f254274d19baf184748d50d7fc41
      Handler: index.handler
      Role:
        Ref: AutomationRole
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
