AWSTemplateFormatVersion: '2010-09-09'
Description: 'simple template for testing lambda deployment function'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'simple-bucket-test-${AWS::Region}'
Outputs:
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: SSL URL of bucket