AWSTemplateFormatVersion: '2010-09-09'
Description: codepipeline to deploy infrastructure from github repo - deploy once in each region

Parameters:
  AutomationRole:
    Type: String
    Description: "ARN of the role to be used by the CodePipeline service - Get the ARN from the bootstrap stack outputs"
    Default: "arn:aws:iam::892774835300:role/ThousandServersBootstrap-AutomationRole-1HQFBRP4LDTPX"

  InstanceProfileArn:
    Type: String
    Description: "ARN of the role to be used by the EC2 launch config - it is created by app.yml in the first region"
    Default: ""

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "codepipeline-${AWS::Region}-${AWS::AccountId}"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ThousandServers02
      RoleArn:
        !Ref "AutomationRole" 
      ArtifactStore:
        Type: S3
        Location: !Ref "ArtifactBucket"
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: gleizerowicz
                Repo: ThousandServers
                Branch: master
                OAuthToken: REPLACE_OAUTH_TOKEN
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                StackName: ThousandServersAuto
                ActionMode: CREATE_UPDATE
                RoleArn: !Ref AutomationRole
                Capabilities: CAPABILITY_IAM
                TemplatePath: "SourceOutput::infrastructure/02_Automated/app.yml"
                ParameterOverrides: !Sub |
                  { "InstanceProfileArn": "${InstanceProfileArn}" }
              InputArtifacts:
                - Name: SourceOutput
