AWSTemplateFormatVersion: '2010-09-09'
Description: codepipeline to deploy infrastructure from github repo - deploy once in each region

Parameters:
  AutomationRole:
    Type: String
    Description: "ARN of the role to be used by the CodePipeline service - Get the ARN from the bootstrap stack outputs"
    Default: "arn:aws:iam::892774835300:role/ThousandServersBootstrap-AutomationRole-1HQFBRP4LDTPX"

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "codepipeline-${AWS::Region}-${AWS::AccountId}"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ThousandServersMultiRegion
      RoleArn:
        !Ref "AutomationRole" 
      ArtifactStore:
        Type: S3
        Location: !Ref "ArtifactBucket"
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: gleizerowicz
                Repo: ThousandServers
                Branch: master
                OAuthToken: REPLACE_OAUTH_TOKEN
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: deploy-template-lambda-LambdaFunction-1NN0S5WFHZ2AL
                UserParameters: "{ \"StackName\": \"ThousandServersAuto\", \"TemplateFile\": \"infrastructure/02_Automated/app.yml\", \"RegionsFile\": \"infrastructure/02_Automated/regions.json\" }"
              InputArtifacts:
                - Name: SourceOutput
